"""
Pre-computed report aggregates.

Daily reports are generated by a Celery beat task at midnight.
Weekly/Monthly/Quarterly/Yearly reports roll up from daily reports.
"""
from django.db import models


class ReportPeriod(models.TextChoices):
    DAILY = "daily", "Daily"
    WEEKLY = "weekly", "Weekly"
    MONTHLY = "monthly", "Monthly"
    QUARTERLY = "quarterly", "Quarterly"
    YEARLY = "yearly", "Yearly"


class _ReportBase(models.Model):
    """Shared fields for all report aggregates. Abstract."""
    id = models.BigAutoField(primary_key=True)
    period_start = models.DateField(db_index=True)
    period_end = models.DateField(db_index=True)

    total_transactions = models.PositiveIntegerField(default=0)
    completed_transactions = models.PositiveIntegerField(default=0)
    rejected_transactions = models.PositiveIntegerField(default=0)

    # Totals by currency (JSON for flexibility across USD/EUR/GBP/...).
    # Shape: {"USD": "12345.67", "EUR": "890.12", ...}
    received_by_currency = models.JSONField(default=dict)
    fees_by_currency = models.JSONField(default=dict)

    total_pkr_sent = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    total_fee_pkr = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    generated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ["-period_start"]


class DailyReport(_ReportBase):
    date = models.DateField(unique=True, db_index=True)

    class Meta(_ReportBase.Meta):
        db_table = "reports_daily"

    def __str__(self):
        return f"Daily {self.date}"


class WeeklyReport(_ReportBase):
    year = models.PositiveSmallIntegerField()
    week = models.PositiveSmallIntegerField()  # ISO week

    class Meta(_ReportBase.Meta):
        db_table = "reports_weekly"
        unique_together = [("year", "week")]

    def __str__(self):
        return f"Week {self.week}, {self.year}"


class MonthlyReport(_ReportBase):
    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()

    class Meta(_ReportBase.Meta):
        db_table = "reports_monthly"
        unique_together = [("year", "month")]

    def __str__(self):
        return f"{self.year}-{self.month:02d}"
