# Generated by Django 5.1.4 on 2026-04-16 21:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import myapp.Models.Auth_models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', myapp.Models.Auth_models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_base', models.BooleanField(default=False, help_text='True for PKR — the currency we pay out in.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('completed_transactions', models.PositiveIntegerField(default=0)),
                ('rejected_transactions', models.PositiveIntegerField(default=0)),
                ('received_by_currency', models.JSONField(default=dict)),
                ('fees_by_currency', models.JSONField(default=dict)),
                ('total_pkr_sent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fee_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'db_table': 'reports_daily',
                'ordering': ['-period_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PakistaniBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/pk/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banks_pk',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('state_change', 'State change'), ('rate_change', 'Rate change'), ('fee_change', 'Fee change')], db_index=True, max_length=30)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rate', serialize=False, to='myapp.currency')),
                ('rate_to_pkr', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(choices=[('live', 'Live API'), ('manual', 'Manual Override')], default='live', max_length=10)),
                ('manual_override_until', models.DateTimeField(blank=True, help_text="While set, live fetches won't overwrite this rate.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, help_text='IBAN (PK..)', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.pakistanibank')),
            ],
            options={
                'db_table': 'customer_bank_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('cnic_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format 12345-1234567-1 or 13 digits.', regex='^\\d{5}-?\\d{7}-?\\d{1}$')])),
                ('cnic_front', models.ImageField(upload_to='cnic/front/')),
                ('cnic_back', models.ImageField(upload_to='cnic/back/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(db_index=True, max_length=3)),
                ('rate_to_pkr', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exchange_rate_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForeignBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('EU', 'European Union')], db_index=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/foreign/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banks_foreign',
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMerchantAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=80)),
                ('iban', models.CharField(blank=True, help_text='IBAN / routing / SWIFT', max_length=80)),
                ('routing_number', models.CharField(blank=True, max_length=40)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_accounts', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.foreignbank')),
            ],
            options={
                'db_table': 'customer_merchant_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_company', models.CharField(blank=True, max_length=150)),
                ('sender_bank_name', models.CharField(max_length=150)),
                ('sender_account_last4', models.CharField(max_length=10)),
                ('external_transaction_id', models.CharField(help_text="Unique ID from sender's bank / platform", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('screenshot_transaction', models.ImageField(upload_to='proofs/txn/')),
                ('screenshot_email', models.ImageField(blank=True, null=True, upload_to='proofs/email/')),
                ('extra_document', models.FileField(blank=True, null=True, upload_to='proofs/docs/')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='1 unit of `currency` = X PKR', max_digits=14, null=True)),
                ('fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage charged as our fee', max_digits=5, null=True)),
                ('fee_amount_foreign', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in the received currency', max_digits=18, null=True)),
                ('net_amount_foreign', models.DecimalField(blank=True, decimal_places=2, help_text='amount - fee_amount_foreign', max_digits=18, null=True)),
                ('gross_pkr', models.DecimalField(blank=True, decimal_places=2, help_text='amount * exchange_rate (before fee, reference only)', max_digits=18, null=True)),
                ('net_pkr', models.DecimalField(blank=True, decimal_places=2, help_text='net_amount_foreign * exchange_rate — what customer actually receives', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted by Customer'), ('under_review', 'Under Review'), ('verified', 'Verified — Awaiting PKR Transfer'), ('pkr_sent', 'PKR Sent to Customer'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('accountant_notes', models.TextField(blank=True)),
                ('accountant_document', models.FileField(blank=True, null=True, upload_to='accountant/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='myapp.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_payments', to=settings.AUTH_USER_MODEL)),
                ('merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='myapp.customermerchantaccount')),
            ],
            options={
                'db_table': 'incoming_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('completed_transactions', models.PositiveIntegerField(default=0)),
                ('rejected_transactions', models.PositiveIntegerField(default=0)),
                ('received_by_currency', models.JSONField(default=dict)),
                ('fees_by_currency', models.JSONField(default=dict)),
                ('total_pkr_sent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fee_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'reports_monthly',
                'ordering': ['-period_start'],
                'abstract': False,
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OutgoingPKRTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_transaction_id', models.CharField(help_text='Reference from our bank', max_length=100)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='transfers/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pkr_transfers', to='myapp.customerbankaccount')),
                ('incoming_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer', to='myapp.incomingpayment')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outgoing_pkr_transfers',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerShare',
            fields=[
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='share', serialize=False, to='myapp.partner')),
                ('percentage', models.DecimalField(decimal_places=3, help_text='Percentage of total collected fee (NOT of transaction amount).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_shares',
            },
        ),
        migrations.CreateModel(
            name='PartnerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_snapshot', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fee_total_foreign', models.DecimalField(decimal_places=2, help_text="Total fee collected (in the transaction's foreign currency).", max_digits=18)),
                ('fee_total_pkr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_foreign', models.DecimalField(decimal_places=2, help_text="This partner's share of the foreign-currency fee.", max_digits=18)),
                ('amount_pkr', models.DecimalField(decimal_places=2, help_text="This partner's share of the fee in PKR.", max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='myapp.partner')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_ledger_entries', to='myapp.incomingpayment')),
            ],
            options={
                'db_table': 'partner_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='myapp.incomingpayment')),
            ],
            options={
                'db_table': 'transaction_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('completed_transactions', models.PositiveIntegerField(default=0)),
                ('rejected_transactions', models.PositiveIntegerField(default=0)),
                ('received_by_currency', models.JSONField(default=dict)),
                ('fees_by_currency', models.JSONField(default=dict)),
                ('total_pkr_sent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fee_pkr', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'reports_weekly',
                'ordering': ['-period_start'],
                'abstract': False,
                'unique_together': {('year', 'week')},
            },
        ),
        migrations.CreateModel(
            name='CustomerFeeConfig',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fee_config', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fee_percentage', models.DecimalField(decimal_places=2, help_text='Overrides the system-default fee percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_fee_configs',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_logs_target__f350f5_idx'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['currency_code', '-created_at'], name='exchange_ra_currenc_7c4fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingpayment',
            index=models.Index(fields=['customer', 'status'], name='incoming_pa_custome_245b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingpayment',
            index=models.Index(fields=['currency', 'created_at'], name='incoming_pa_currenc_53df9d_idx'),
        ),
        migrations.AddField(
            model_name='partnershare',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['partner', '-created_at'], name='partner_led_partner_cd48e4_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['payment'], name='partner_led_payment_a0fff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerledgerentry',
            unique_together={('partner', 'payment')},
        ),
    ]
