# Generated by Django 4.2.30 on 2026-04-17 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingpayment',
            name='verified_document',
            field=models.FileField(blank=True, help_text='Optional proof the accountant uploads while verifying.', null=True, upload_to='proofs/verification/'),
        ),
        migrations.AddField(
            model_name='incomingpayment',
            name='verified_note',
            field=models.TextField(blank=True, help_text='Short note the accountant writes when verifying documents.'),
        ),
    ]
