# Generated by Django 4.2.30 on 2026-04-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_incomingpayment_verified_by_and_more'),
        ('myapp', '0004_payment_verification_fields'),
    ]

    operations = [
    ]
