# Generated by Django 4.2.30 on 2026-04-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('state_change', 'State change'), ('rate_change', 'Rate change'), ('fee_change', 'Fee change'), ('kyc_review', 'KYC review'), ('payment_verify', 'Payment verification'), ('password_reset', 'Password reset'), ('toggle_active', 'Toggle active')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable short label of the target object at log time.', max_length=200),
        ),
    ]
