# Generated by Django 4.2.30 on 2026-04-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_email_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='email_otps_email_4a8bd3_idx',
            old_name='email_otps_email_purpose_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='myapp_expen_spent_o_30ad2b_idx',
            old_name='myapp_expen_spent_o_c52b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='myapp_expen_currenc_3c135f_idx',
            old_name='myapp_expen_currenc_fe823a_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='myapp.currency'),
        ),
    ]
