# Generated by Django 4.2.30 on 2026-04-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_payment_methods_and_flow_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomingpayment',
            new_name='incoming_pa_status_90e4ef_idx',
            old_name='incoming_pa_status_is_stal_idx',
        ),
        migrations.RemoveField(
            model_name='incomingpayment',
            name='merchant_account',
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='myapp.paymentmethod'),
        ),
    ]
