# Generated by Django 4.2.30 on 2026-04-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_payment_method_config_and_allowed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='customer_cl_custome_4c02ca_idx',
            old_name='customer_cli_custome_b3d2a4_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='customer_cl_custome_6e5700_idx',
            old_name='customer_cli_custome_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customerallowedpaymentmethod',
            new_name='customer_al_custome_411e5d_idx',
            old_name='cust_allow_pm_cust_prim_idx',
        ),
        migrations.RenameIndex(
            model_name='customercompany',
            new_name='customer_co_custome_74b79d_idx',
            old_name='customer_co_custome_prim_idx',
        ),
        migrations.AlterField(
            model_name='customerallowedpaymentmethod',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
