# Generated by Django 4.2.30 on 2026-04-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_invoices'),
        ('myapp', '0018_rename_customer_cli_custome_b3d2a4_idx_customer_cl_custome_4c02ca_idx_and_more'),
    ]

    operations = [
    ]
