# Generated by Django 4.2.30 on 2026-04-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_merge_20260422_0639'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_custome_90a13d_idx',
            old_name='invoices_cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_custome_38a61a_idx',
            old_name='invoices_cust_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_client__6ec4db_idx',
            old_name='invoices_client_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_company_479483_idx',
            old_name='invoices_company_created_idx',
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
