# Generated by Django 4.2.30 on 2026-04-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_invoice_payment_methods'),
        ('myapp', '0020_rename_invoices_cust_status_idx_invoices_custome_90a13d_idx_and_more'),
    ]

    operations = [
    ]
