# Generated by Django 4.2.30 on 2026-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_20260422_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaymentmethod',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
