# Generated by Django 4.2.30 on 2026-04-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_customer_feature_access'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerfeatureaccess',
            new_name='customer_fe_user_id_1b913b_idx',
            old_name='cust_feat_user_key_idx',
        ),
        migrations.RenameIndex(
            model_name='customerfeatureaccess',
            new_name='customer_fe_feature_1378fa_idx',
            old_name='cust_feat_key_en_idx',
        ),
    ]
