# Generated by Django 4.2.30 on 2026-04-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_invoice_pdf_theme'),
        ('myapp', '0024_rename_cust_feat_user_key_idx_customer_fe_user_id_1b913b_idx_and_more'),
    ]

    operations = [
    ]
