# Generated by Django 4.2.30 on 2026-04-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_internal_transactions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internaltransaction',
            new_name='internal_tr_occurre_d04a01_idx',
            old_name='internal_tx_occur_src_idx',
        ),
        migrations.RenameIndex(
            model_name='internaltransaction',
            new_name='internal_tr_occurre_1b46a2_idx',
            old_name='internal_tx_occur_dst_idx',
        ),
        migrations.RenameIndex(
            model_name='internaltransaction',
            new_name='internal_tr_currenc_cd11c1_idx',
            old_name='internal_tx_curr_occur_idx',
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transactions', to='myapp.currency'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='fee_currency',
            field=models.ForeignKey(blank=True, help_text='Currency the fee was charged in. Usually the same as `currency`; left null = inherit from `currency`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_transaction_fees', to='myapp.currency'),
        ),
    ]
