# Generated by Django 4.2.30 on 2026-04-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_internal_tx_occur_src_idx_internal_tr_occurre_d04a01_idx_and_more'),
        ('myapp', '0028_widen_internal_account_fields'),
    ]

    operations = [
    ]
