# Generated by Django 4.2.30 on 2026-05-05 20:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_customerprofile_resubmit_diff'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='dispatches_custome_37c4aa_idx',
            old_name='dispatches_customer_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='dispatches_custome_67bb35_idx',
            old_name='dispatches_customer_pkup_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='dispatches_custome_f27e72_idx',
            old_name='dispatches_customer_paid_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='dispatches_company_2fa0fd_idx',
            old_name='dispatches_company_pkup_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='dispatches_driver__636b35_idx',
            old_name='dispatches_driver_pkup_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchcompany',
            new_name='dispatch_co_custome_d43e70_idx',
            old_name='dispatch_co_custome_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchcompany',
            new_name='dispatch_co_custome_1a0393_idx',
            old_name='dispatch_co_custome_name_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchdriver',
            new_name='dispatch_dr_custome_5cb93b_idx',
            old_name='dispatch_dr_custome_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchdriver',
            new_name='dispatch_dr_custome_03a7be_idx',
            old_name='dispatch_dr_custome_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchdriver',
            new_name='dispatch_dr_company_f29283_idx',
            old_name='dispatch_dr_company_arch_idx',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_fee_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional flat dispatch fee. If non-zero, overrides the percent.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Dispatcher's % of the load rate.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatcher_name',
            field=models.CharField(blank=True, default='', help_text='Internal dispatcher / agent who booked the load.', max_length=150),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='extra_stops',
            field=models.TextField(blank=True, default='', help_text='Extra stops between pickup and final dropoff.'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the broker has paid for the load.'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total rate paid by the broker for the load.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='rate_confirmation',
            field=models.FileField(blank=True, help_text='Optional rate-confirmation PDF uploaded by the dispatcher.', null=True, upload_to='dispatches/rate_confirmation/'),
        ),
        migrations.AlterField(
            model_name='dispatchcompany',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. Archived companies stay linked to existing loads but disappear from the picker.'),
        ),
        migrations.AlterField(
            model_name='dispatchcompany',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Private notes the customer keeps about this trucking company. Not shown on any invoice.'),
        ),
        migrations.AlterField(
            model_name='dispatchdriver',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('step_deck', 'Step Deck'), ('box_truck', 'Box Truck'), ('power_only', 'Power Only'), ('hotshot', 'Hotshot'), ('conestoga', 'Conestoga'), ('other', 'Other')], default='', help_text='Default truck type — auto-fills the load form.', max_length=32),
        ),
    ]
