# Generated by Django 4.2.30 on 2026-06-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_bank_audit_module'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaudit',
            new_name='bank_audits_bank_97efea_idx',
            old_name='bank_audits_bank_idx',
        ),
        migrations.AlterField(
            model_name='bankaudit',
            name='bank',
            field=models.CharField(choices=[('cashapp', 'Cash App'), ('amex', 'American Express'), ('us_bank', 'US Bank'), ('generic', 'Generic / Other')], db_index=True, help_text="Which bank's statement format was reconciled.", max_length=20),
        ),
        migrations.AlterField(
            model_name='customerallowedpaymentmethod',
            name='admin_excluded',
            field=models.BooleanField(default=False, help_text='True when an admin explicitly removed this auto-assigned default for this specific customer. Prevents re-assignment on default sync runs.'),
        ),
        migrations.AlterField(
            model_name='customerallowedpaymentmethod',
            name='auto_assigned',
            field=models.BooleanField(default=False, help_text='True when created automatically because payment_method.is_default=True. False for manually granted methods.'),
        ),
        migrations.AlterField(
            model_name='expensedistribution',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Null means this slice belongs to the company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_distributions', to='myapp.partner'),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Tangent rate: 1 unit of `currency` = X PKR — the rate given to the customer and used to compute net_pkr. Must never exceed real_exchange_rate.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='fee_allocation',
            field=models.JSONField(blank=True, help_text='Custom fee split when transaction fee < sum of partner shares. JSON: {"company": <pct_of_fee>, "partners": {"<uuid>": <pct_of_fee>}}', null=True),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='real_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Actual market rate at time of transfer (admin-editable). Company rate-spread profit = (real - tangent) * total_amount.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='fee_dist_partner',
            field=models.ForeignKey(blank=True, help_text='Partner who absorbs the fee (when fee_dist_type=partner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_tx_fees', to='myapp.partner'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='fee_dist_type',
            field=models.CharField(choices=[('company', 'Company'), ('partner', 'Single partner'), ('custom', 'Custom split (see expense distributions)')], default='company', help_text='Who absorbs this transfer fee.', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerledgerentry',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, help_text="This partner's share of the fee in PKR (at tangent rate).", max_digits=18),
        ),
        migrations.AlterField(
            model_name='partnerledgerentry',
            name='rate_spread_profit_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Company's rate-spread profit from this partner's payout portion: (real_rate - tangent_rate) * amount_foreign", max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='partnerledgerentry',
            name='real_exchange_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Actual market rate at time of transaction (for spread calculation).', max_digits=14, null=True),
        ),
    ]
