# Generated by Django 4.2.30 on 2026-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_payment_method_deposit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransaction',
            name='card_profit_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PKR RECEIVED into our Pakistani banks from this card transaction: (amount + fee_amount) × card_dollar_rate. Despite the legacy column name this is NOT company profit — it is part of the PKR reconciliation pool, alongside USA→PK bank transfers. Exposed by the API as `card_received_pkr`.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank / wire / processing fee charged on this transfer, in `currency`. For bank transfers it is auto-pushed into Expenses in the BANKING category. For CREDIT-CARD transactions the fee is NOT an expense: it is converted along with the spend and folded into card_profit_pkr, which represents PKR RECEIVED into our Pakistani banks (not company profit).', max_digits=18),
        ),
    ]
