# Generated by Django 5.0.14 on 2026-07-11 18:19

from django.db import migrations, models


def _derive(code):
    """Mirror of PaymentMethod.derive_method_type (kept local so the
    migration is self-contained and independent of model code)."""
    c = (code or "").lower().replace("-", "_").replace(" ", "_")
    if "zelle" in c:
        return "zelle"
    if "cash" in c:
        return "cashapp"
    if "payoneer" in c:
        return "payoneer"
    if "ach" in c or "wire" in c:
        return "ach_wire"
    return "other"


def backfill_method_type(apps, schema_editor):
    PaymentMethod = apps.get_model("myapp", "PaymentMethod")
    for m in PaymentMethod.objects.all():
        if not m.method_type:
            m.method_type = _derive(m.code)
            m.save(update_fields=["method_type"])


def noop_reverse(apps, schema_editor):
    # Reversing just clears the derived value — harmless.
    PaymentMethod = apps.get_model("myapp", "PaymentMethod")
    PaymentMethod.objects.update(method_type="")


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_internaltransaction_card_profit_pkr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(blank=True, choices=[('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('ach_wire', 'ACH / Wire'), ('payoneer', 'Payoneer'), ('other', 'Other')], db_index=True, default='', help_text='Payment-method family (Zelle, Cash App, …). Drives the icon and grouping so multiple accounts of the same kind can coexist. Auto-derived from the code when left blank.', max_length=32),
        ),
        migrations.RunPython(backfill_method_type, noop_reverse),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deposit_account__isnull', False)), fields=('deposit_account',), name='uniq_paymentmethod_deposit_account'),
        ),
    ]
