# Generated by Django 6.0.7 on 2026-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_pkr_converter_vendor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overdue_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When an overdue reminder was last emailed to the client.', null=True),
        ),
    ]
