# Generated by Django 6.0.7 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0056_invoice_overdue_reminder_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpkrpayment",
            name="is_auto_generated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="vendorpkrpayment",
            name="is_void",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="vendorpkrpayment",
            name="void_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="vendorpkrpayment",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
