# Generated by Django 6.0.7 on 2026-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_invoice_overdue_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password reset'), ('email_verification', 'Email verification')], db_index=True, max_length=20),
        ),
    ]
