# Generated by Django 6.0.7 on 2026-08-06 15:54

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def forwards_func(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    
    # 1. Admins are exempt
    User.objects.filter(role="admin").update(email_verified=True, verification_deadline=None)
    
    # 2. Existing non-admins get a 14-day grace period
    grace_period = timezone.now() + timedelta(days=14)
    
    User.objects.exclude(role="admin").filter(email_verified=False).update(
        is_active=True,
        email_verified=False,
        verification_deadline=grace_period
    )

    # Do not send email from a database migration. Migrations must remain
    # deterministic and safe to run during deploys where an email provider may
    # be unavailable or rate limited. Notices are sent by an explicit command.

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_user_email_verified_user_verification_deadline_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
