# Generated by Django 6.0.7 on 2026-08-06 15:54

import time
from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def forwards_func(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    
    # 1. Admins are exempt
    User.objects.filter(role="admin").update(email_verified=True, verification_deadline=None)
    
    # 2. Existing non-admins get a 14-day grace period
    grace_period = timezone.now() + timedelta(days=14)
    
    # We must fetch them before bulk updating to send emails
    users_to_update = list(User.objects.exclude(role="admin").filter(email_verified=False))
    
    User.objects.exclude(role="admin").filter(email_verified=False).update(
        is_active=True,
        email_verified=False,
        verification_deadline=grace_period
    )
    
    # Send notice emails
    from myapp.Utils.email_tasks import send_email_async
    for u in users_to_update:
        send_email_async(
            to=[u.email],
            subject="Action Required: Verify Your Email",
            template="auth/email_verification_notice",
            context={"name": u.full_name or "User"}
        )
        time.sleep(0.05)  # slight delay to avoid thread creation spike

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_user_email_verified_user_verification_deadline_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
