# Generated by Django 6.0.7 on 2026-09-04 21:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_existing_receipts(apps, schema_editor):
    OutgoingPKRTransfer = apps.get_model('myapp', 'OutgoingPKRTransfer')
    OutgoingPKRTransferReceipt = apps.get_model('myapp', 'OutgoingPKRTransferReceipt')
    for transfer in OutgoingPKRTransfer.objects.exclude(receipt='').exclude(receipt__isnull=True):
        OutgoingPKRTransferReceipt.objects.create(
            transfer=transfer,
            file=transfer.receipt,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_accountant_email_verified_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingPKRTransferReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='transfers/receipts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='myapp.outgoingpkrtransfer')),
            ],
            options={
                'db_table': 'outgoing_pkr_transfer_receipts',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(backfill_existing_receipts, reverse_code=migrations.RunPython.noop),
    ]
