# Generated by Django 6.0.7 on 2026-09-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_historical_transfers(apps, schema_editor):
    OutgoingPKRTransfer = apps.get_model('myapp', 'OutgoingPKRTransfer')
    from datetime import date
    from django.db.models import Q, F
    sept_1 = date(2026, 9, 1)

    hist_qs = OutgoingPKRTransfer.objects.filter(
        Q(transfer_date__lt=sept_1) | (Q(transfer_date__isnull=True) & Q(sent_at__lt=sept_1))
    )
    hist_qs.update(
        bank_verified=True,
        bank_verification_status='verified',
        bank_verification_source='historical_backfill',
        bank_verification_notes='Automatically verified: Historical transfer prior to September 2026',
        bank_verified_at=F('sent_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_outgoingpkrtransfer_deduction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_statement_matched_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_statement_ref',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verification_source',
            field=models.CharField(choices=[('cron', 'Automated Cronjob'), ('manual', 'Manual Review / Resolved'), ('historical_backfill', 'Historical Backfill')], default='cron', max_length=30),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('discrepancy', 'Flagged / Discrepancy'), ('unmatched', 'Unmatched / Not Found')], db_index=True, default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this outgoing transfer was verified against our bank statement'),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingpkrtransfer',
            name='bank_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who manually verified or resolved discrepancy; null if cron/automated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_verified_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingpkrtransfer',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, help_text='Final PKR amount sent to the customer after deductions', max_digits=18),
        ),
        migrations.AlterField(
            model_name='outgoingpkrtransfer',
            name='transfer_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the PKR were transferred to the customer bank account from ours', null=True),
        ),
        migrations.RunPython(backfill_historical_transfers, reverse_code=migrations.RunPython.noop),
    ]

