# Generated by Django 6.0.7 on 2026-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_ubl_fallback_proxies_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='cron', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('newly_inserted', models.IntegerField(default=0)),
                ('skipped_duplicates', models.IntegerField(default=0)),
                ('credits_inserted', models.IntegerField(default=0)),
                ('debits_inserted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'bank_sync_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BankStatementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=64)),
                ('channel_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cr_dr', models.CharField(db_index=True, max_length=10)),
                ('tran_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('equiv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('equiv_currency', models.CharField(blank=True, max_length=10)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('running_balance_currency', models.CharField(blank=True, max_length=10)),
                ('tran_date', models.DateField(blank=True, db_index=True, null=True)),
                ('post_date', models.DateField(blank=True, db_index=True, null=True)),
                ('tran_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('tran_desc', models.TextField(blank=True)),
                ('tran_desc2', models.TextField(blank=True)),
                ('tran_desc3', models.TextField(blank=True)),
                ('tran_desc4', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('unique_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'bank_statement_records',
                'ordering': ['-tran_date', '-id'],
                'indexes': [models.Index(fields=['tran_date', 'cr_dr'], name='bank_statem_tran_da_19e3a3_idx'), models.Index(fields=['account_number', 'tran_date'], name='bank_statem_account_03ac25_idx')],
            },
        ),
    ]
