# Generated by Django 6.0.7 on 2026-09-28 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_banksyncjob_alter_systemsetting_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='cnic/back/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='cnic/front/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format 12345-1234567-1 or 13 digits.', regex='^\\d{5}-?\\d{7}-?\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('objections', 'Objections Raised'), ('resubmitted', 'Resubmitted for Review')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
