# Generated by Django 6.0.7 on 2026-10-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksyncjob',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='banksyncjob',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='banksyncjob',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
