"""
Invoice endpoints — admin + accountant can generate customer-facing PDFs.

    GET  /transactions/payments/<id>/invoice.pdf
         Single-transaction invoice.

    POST /transactions/payments/invoice-bulk.pdf
         Body: { "ids": ["uuid1", "uuid2", ...] }
         Bulk invoice covering many transactions in one PDF.

Both endpoints return customer-facing data only — no partner payouts, no
profit figures, no internal annotations.
"""
from datetime import datetime
import re

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from myapp.Models.Transaction_models import IncomingPayment
from myapp.Utils.permissions import IsAdminOrAccountant


def _customer_slug(customer):
    """
    Turn a customer object into a filesystem-safe name fragment:
      "Ali Khan"                → "ali-khan"
      "john.doe@example.com"    → "john-doe"
      None / missing            → "customer"
    Keeps filenames neat across Windows/macOS/Linux without breaking on
    unicode, apostrophes, commas, etc.
    """
    raw = ""
    if customer is not None:
        raw = getattr(customer, "full_name", "") or ""
        if not raw:
            email = getattr(customer, "email", "") or ""
            raw = email.split("@")[0] if email else ""
    raw = raw.strip().lower()
    # Replace non-alphanumerics with hyphens, collapse duplicates, trim edges
    raw = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return raw[:40] or "customer"


def _subtitle_single(payment):
    parts = [payment.reference or "—"]
    if payment.created_at:
        parts.append(payment.created_at.strftime("%b %d, %Y"))
    return " · ".join(parts)


def _subtitle_bulk(payments):
    count = len(payments)
    if count == 0:
        return "0 transactions"
    # Date range across selected payments
    dates = [p.created_at for p in payments if p.created_at]
    if dates:
        dmin, dmax = min(dates), max(dates)
        if dmin.date() == dmax.date():
            return f"{count} transactions · {dmin.strftime('%b %d, %Y')}"
        return (f"{count} transactions · "
                f"{dmin.strftime('%b %d, %Y')} — {dmax.strftime('%b %d, %Y')}")
    return f"{count} transactions"


@api_view(["GET"])
@permission_classes([IsAuthenticated, IsAdminOrAccountant])
def single_invoice_pdf(request, payment_id):
    """Generate a single-transaction invoice PDF."""
    from myapp.Utils.pdf_report import PDFReportBuilder
    from myapp.Views.Invoice_composers import compose_single_invoice

    payment = get_object_or_404(
        IncomingPayment.objects.select_related(
            "customer", "currency", "merchant_account",
        ),
        pk=payment_id,
    )

    sections = compose_single_invoice(payment)

    metadata = {
        "Reference":    payment.reference,
        "External ID":  payment.external_transaction_id or "—",
        "Date":         (payment.created_at.strftime("%b %d, %Y")
                         if payment.created_at else "—"),
        "Currency":     payment.currency_id,
        "Generated By": request.user.full_name or request.user.email,
        "Generated On": datetime.now().strftime("%b %d, %Y at %H:%M"),
    }

    builder = PDFReportBuilder(
        title="Transaction Invoice",
        subtitle=_subtitle_single(payment),
        metadata=metadata,
    )
    pdf_bytes = builder.build(sections)

    # Include customer name in filename for easier filing. Fall back to
    # email local-part, then to a generic label. Slug to keep it
    # filesystem-safe across OSes.
    customer_slug = _customer_slug(payment.customer)
    filename = f"invoice-{customer_slug}-{payment.reference or payment.id}.pdf"
    resp = HttpResponse(pdf_bytes, content_type="application/pdf")
    resp["Content-Disposition"] = f'attachment; filename="{filename}"'
    return resp


@api_view(["POST"])
@permission_classes([IsAuthenticated, IsAdminOrAccountant])
def bulk_invoice_pdf(request):
    """Generate a bulk invoice PDF for the given transaction IDs."""
    from myapp.Utils.pdf_report import PDFReportBuilder
    from myapp.Views.Invoice_composers import compose_bulk_invoice

    ids = request.data.get("ids") or []
    if not isinstance(ids, (list, tuple)) or not ids:
        return Response({"detail": "Provide a non-empty list of transaction ids."},
                        status=400)
    if len(ids) > 500:
        return Response({"detail": "Too many transactions — limit is 500 per invoice."},
                        status=400)

    payments = list(
        IncomingPayment.objects
        .filter(id__in=ids)
        .select_related("customer", "currency", "merchant_account")
        .order_by("-created_at")
    )
    if not payments:
        return Response({"detail": "No transactions found with those ids."},
                        status=404)

    sections = compose_bulk_invoice(payments)

    # If every payment belongs to one customer, surface that in the subtitle.
    customers = {p.customer_id for p in payments}
    metadata = {
        "Transactions": str(len(payments)),
        "Customers":    str(len(customers)),
        "Generated By": request.user.full_name or request.user.email,
        "Generated On": datetime.now().strftime("%b %d, %Y at %H:%M"),
    }

    builder = PDFReportBuilder(
        title="Bulk Transaction Invoice",
        subtitle=_subtitle_bulk(payments),
        metadata=metadata,
    )
    pdf_bytes = builder.build(sections)

    # When every transaction belongs to the same customer, fold the name
    # into the filename so the admin can tell at a glance whose invoice
    # this is without opening it.
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    if len(customers) == 1:
        only = next(iter(payments)).customer
        customer_slug = _customer_slug(only)
        filename = f"bulk-invoice-{customer_slug}-{stamp}.pdf"
    else:
        filename = f"bulk-invoice-{stamp}.pdf"
    resp = HttpResponse(pdf_bytes, content_type="application/pdf")
    resp["Content-Disposition"] = f'attachment; filename="{filename}"'
    return resp
